# POST https://frendy-rasa-bot-ilsxqqnpkq-uc.a.run.app/webhooks/custom_rest/webhook HTTP/1.1
# Content-Type: application/json

# {
#     "sender":"testmeta0129",
#     "message":"hi",
#     "metadata": {"metadata":"1212113131131sdsds"}
    
# }

# POST http://localhost:5005/webhooks/custom_rest/webhook HTTP/1.1
# Content-Type: application/json

# {
#     "sender":"2121",
#     "message":"i want to order a product",
#     "metadata": {"metadata":"1212113131131sdsds"}
    
# }


POST http://localhost:5000/channels/tw-wa/webhook HTTP/1.1
Content-Type: application/json

{
    "From":"whata:+2121",
    "Body":"hi"
    
}

