# POST https://frendy-rasa-bot-ilsxqqnpkq-uc.a.run.app/webhooks/custom_rest/webhook HTTP/1.1
# Content-Type: application/json

# {
#     "sender":"testmeta0129",
#     "message":"hahahaha@@@@@@@@@@@@---------------------aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
#     "metadata": {"metadata":"1212113131131sdsds"}
    
# }

POST http://localhost:5005/webhooks/custom_rest/webhook HTTP/1.1
Content-Type: application/json

{
    "sender":"9989921",
    "message":"order product",
    "metadata": {"metadata":"1212113131131sdsds"}
    
}

